import { enumerate, repeat } from "$lib/utils";

export type Config = {
    dots: string[],
    dashes: string[],
    separators: string[],
    letterSpacing: number,
    wordSpacing: number,
}

// Generated by chatgpt; Correctness is not guaranteed
const morseCodeMap = {
    "A": ".-",
    "B": "-...",
    "C": "-.-.",
    "D": "-..",
    "E": ".",
    "F": "..-.",
    "G": "--.",
    "H": "....",
    "I": "..",
    "J": ".---",
    "K": "-.-",
    "L": ".-..",
    "M": "--",
    "N": "-.",
    "O": "---",
    "P": ".--.",
    "Q": "--.-",
    "R": ".-.",
    "S": "...",
    "T": "-",
    "U": "..-",
    "V": "...-",
    "W": ".--",
    "X": "-..-",
    "Y": "-.--",
    "Z": "--..",
    "0": "-----",
    "1": ".----",
    "2": "..---",
    "3": "...--",
    "4": "....-",
    "5": ".....",
    "6": "-....",
    "7": "--...",
    "8": "---..",
    "9": "----."
};

// will throw if there is invalid character 
export function encode(text: string, { dashes, dots, letterSpacing, wordSpacing, separators }: Config) {
    let dotCount = 0
    let dashCount = 0
    let separatorCount = 0
    let out = ""
    const words = text.toUpperCase().split(' ').filter(it => it.length > 0)

    for (const [word, wordIndex] of enumerate(words)) {
        for (const [c, i] of enumerate(word.split(''))) {
            const intermediate = morseCodeMap[c as keyof typeof morseCodeMap]
            for (const symbol of intermediate) {
                if (symbol === ".") {
                    out += dots[dotCount % dots.length]
                    dotCount++
                } else { // -
                    out += dashes[dashCount % dashes.length]
                    dashCount++
                }
            }
            // Space between letter
            // unless last character
            if (i !== word.length - 1) {
                repeat(letterSpacing, () => {
                    out += separators[separatorCount % separators.length]
                    separatorCount++
                })
            }
        }
        // Space between word
        if (wordIndex !== words.length - 1) {
            repeat(wordSpacing, () => {
                out += separators[separatorCount % separators.length]
                separatorCount++
            })
        }

    }

    console.log(out)

    return out
}

export function decode(morse: string, { dashes, dots, letterSpacing, wordSpacing, separators }: Config) {

}